### PR TITLE
Fixed major setState bug with version 3.0 & 3.0.1

### LINKED ISSUE #168: Error in first run after upgrade to v3.0.0
Hi,
After updating the plugin version from 2.5.4 to **3.0.0**, an error will be displayed below the first run.

But after a few seconds the animation starts and works

I did not change the code and just updated the plugin and after the update this problem occurred

My Code:
```
                    SizedBox(
                      height: 100,
                      child: FadeAnimatedTextKit(
                        onTap: () {
                          print("Tap Event");
                        },
                        isRepeatingAnimation: true,
                        text: [
                          "do IT!",
                          "do it RIGHT!!",
                          "do it RIGHT NOW!!!"
                        ],
                        textStyle: TextStyle(
                            fontSize: 27.0,
                            fontWeight: FontWeight.w400,
                          color: Colors.white
                        ),
                        textAlign: TextAlign.start,
                      ),
                    ),

```
**Expected behavior**
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AnimatedBuilder(animation: AnimationController#f1944(▶ 0.942), dirty, state: _AnimatedState#da5af):
The getter 'value' was called on null.
Receiver: null
Tried calling: value

The relevant error-causing widget was: 
  FadeAnimatedTextKit file:///E:/Projects/Android/robo_investment/lib/app.dart:112:30
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FadeAnimatedText.animatedBuilder (package:animated_text_kit/src/fade.dart:45:24)
#2      _AnimatedTextKitState.build.<anonymous closure> (package:animated_text_kit/src/animated_text.dart:187:32)
#3      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1443:19)
#4      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:181:48)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
**(package:animated_text_kit/src/fade.dart:45:24) :**
```
  @override
  Widget animatedBuilder(BuildContext context, Widget child) {
    return Opacity(
      opacity: **_fadeIn.value** != 1.0 ? _fadeIn.value : _fadeOut.value,
      child: textWidget(text),
    );
  }
```
**Screenshots**
https://i.imgur.com/2s1nTEo.png

**Flutter:**
 Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
 - version 1.22.4
 - channel stable

**Dart:**
 - version  2.10.4

**Android Studio.**
 - version: 4.1.0

### PR DESCRIPTION
**Pull request by awhitford**
* Updated the `example` app to add a _Tap Count_
  * The `setState` triggers a widget rebuild that exposes the #168 issue
  * Reorganized the layout to adjust better to Landscape mode
* Fixed `AnimatedTextKit` to save `AnimatedText` state to accommodate a widget rebuild (which could be triggered by a `setState` during an animation)
  * Resolves #168

### CODE REVIEW

**Review by aagarwal1012 — APPROVED** [review]
lgtm
